default_stages: [ commit ]

repos:
    -   repo: https://github.com/PyCQA/isort
        rev: 5.12.0
        hooks:
            -   id: isort

ci:
    autoupdate_schedule: weekly
    skip: [ ]
    submodules: false
