repos:
    -   repo: local
        hooks:
            -   id: flake8
                name: flake8
                description: flake8 enforcement
                entry: flake8
                language: python
                types: [ python ]
            -   id: isort
                name: isort
                description: isort enforcement
                entry: isort .
                language: python
                types: [ python ]
            -   id: conventional-pre-commit
                name: conventional commit
                description: Checks commit message for Conventional Commits formatting
                entry: conventional-pre-commit
                language: python
