services:
    adminpanel:
        environment:
            - ENVIRONMENT=production
    search:
        environment:
            - ENVIRONMENT=production
    postgres:
        volumes:
            - pgdata_prod:/var/lib/postgresql/data
    es:
        volumes:
            - esdata01_prod:/usr/share/elasticsearch/data

volumes:
    pgdata_prod:
    esdata01_prod:
