services:
    tests:
        platform: ${DOCKER_IMG_PLATFORM:-linux/amd64}
        build:
            context: .
            dockerfile: ./docker/tests/Dockerfile
        env_file: .env
        environment:
            CONTENT_APP_HOST: 0.0.0.0
            CONTENT_APP_PORT: 8000
            REDIS_HOST: redis
            REDIS_PORT: 6379
            ELASTIC_HOST: elasticsearch
            ELASTIC_PORT: 9200
        depends_on:
            elasticsearch:
                condition: service_healthy
            redis:
                condition: service_started
        profiles:
            - tests
        volumes:
            - ./src:/src
            - ./docker/tests/scripts:/scripts
            - ./scripts:/scripts
#        entrypoint: [". ./scripts/wait-dependencies.sh"]
#        command: >
#            bash -c ". ./scripts/wait-dependencies.sh"
        command: sh -c "
            . ./scripts/wait-dependencies.sh
            && python src/main.py
            "

    postgres:
        volumes:
            - postgres_data_test:/var/lib/postgresql/data

    elasticsearch:
        volumes:
            - es_data_test:/usr/share/elasticsearch/data
        ports:
            - ${ELASTIC_PORT}:9200

    redis:
        volumes:
            - redis_data_test:/data

volumes:
    postgres_data_test:
    es_data_test:
    redis_data_test:
