services:
    adminpanel:
        build:
            context: .
            dockerfile: ./adminpanel/docker/app/Dockerfile
        restart: on-failure
        env_file:
            - ./.envs/${ENVIRONMENT:-production}/.env
        environment:
            - ENVIRONMENT=${ENVIRONMENT:-production}
            - COMPOSE_MODE=on
            - POSTGRES_HOST=postgres
            - POSTGRES_PORT=5432
            - CREATE_SUPER_USER=True
        depends_on:
            - postgres
    search:
        build:
            context: .
            dockerfile: ./search/docker/app/Dockerfile
        image: app-search-img
        restart: on-failure
        env_file:
            - ./.envs/${ENVIRONMENT:-production}/.env
        environment:
            - ENVIRONMENT=${ENVIRONMENT:-production}
            - COMPOSE_MODE=on
            - SEARCH_APP_HOST=0.0.0.0
            - SEARCH_APP_PORT=8000
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - ELASTIC_HOST=es
            - ELASTIC_PORT=9200
        depends_on:
            - es
            - redis
    postgres:
        build:
            context: .
            dockerfile: ./adminpanel/docker/postgres/Dockerfile
        restart: on-failure
        env_file:
            - ./.envs/${ENVIRONMENT:-production}/.env
    es:
        build:
            context: .
            dockerfile: ./search/docker/es/Dockerfile
        restart: on-failure
        env_file:
            - ./.envs/${ENVIRONMENT:-production}/.env
        environment:
            - discovery.type=single-node
    redis:
        build:
            context: .
            dockerfile: ./search/docker/redis/Dockerfile
        restart: on-failure
        env_file:
            - ./.envs/${ENVIRONMENT:-production}/.env
