services:
    postgres:
        restart: "no"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:5432

    es:
        restart: "no"
        volumes:
            - es_data:/usr/share/elasticsearch/data
        ports:
            - ${ELASTIC_PORT}:9200

    redis:
        restart: "no"
        volumes:
            - redis_data:/data
        ports:
            - ${REDIS_PORT}:6379


volumes:
    postgres_data:
    es_data:
    redis_data:
