x-base-service: &base-service
    platform: ${DOCKER_IMG_PLATFORM:-linux/amd64}
    profiles:
        - default

x-profiles-adminpanel: &profiles-panel
    profiles:
        - default
        - adminpanel
        - etl

x-profiles-etl: &profiles-etl
    profiles:
        - default
        - etl

services:
    postgres:
        <<: [ *profiles-panel, *base-service ]
        build:
            context: .
            dockerfile: ./docker/postgres/Dockerfile
            args:
                - img=${POSTGRES_IMG}
        env_file: .env
        restart: on-failure
        environment:
            POSTGRES_HOST: 127.0.0.1
            POSTGRES_PORT: 5432

    es:
        <<: [ *profiles-etl, *base-service ]
        build:
            context: .
            dockerfile: ./docker/es/Dockerfile
            args:
                - img=${ELASTICSEARCH_IMG}
        env_file: .env
        restart: on-failure
        environment:
            discovery.type: single-node
            ELASTIC_HOST: 127.0.0.1
            ELASTIC_PORT: 9200

    redis:
        <<: [ *profiles-etl, *base-service ]
        build:
            context: .
            dockerfile: ./docker/redis/Dockerfile
            args:
                - img=${REDIS_IMG}
        env_file: .env
        restart: on-failure
        environment:
            REDIS_HOST: 127.0.0.1
            REDIS_PORT: 6379
