services:
    adminpanel_proxy:
        restart: "no"

    adminpanel:
        restart: "no"
        volumes:
            - ./src/${ADMINPANEL_PKG_NAME}:/${CONTAINER_WORK_DIR}/src/${ADMINPANEL_PKG_NAME}

    content_proxy:
        restart: "no"

    content:
        restart: "no"
        volumes:
            - ./src/${CONTENT_PKG_NAME}:/${CONTAINER_WORK_DIR}/src/${CONTENT_PKG_NAME}

    postgres:
        restart: "no"
        ports:
            - ${POSTGRES_PORT}:5432

    elasticsearch:
        restart: "no"
        ports:
            - ${ELASTIC_PORT}:9200

    redis:
        restart: "no"
        ports:
            - ${REDIS_PORT}:6379
