services:
    tests:
        platform: ${DOCKER_IMG_PLATFORM:-linux/amd64}
        build:
            context: .
            dockerfile: docker/tests/Dockerfile
            args:
                - img=${PYTHON_IMG}
                - work_dir=${CONTAINER_WORK_DIR}
        env_file: .env
        environment:
            CONTENT_APP_HOST: 0.0.0.0
            CONTENT_APP_PORT: ${CONTENT_APP_PORT}
            REDIS_HOST: redis
            REDIS_PORT: 6379
            ELASTIC_HOST: elasticsearch
            ELASTIC_PORT: 9200
        depends_on:
            - elasticsearch
            - redis
        profiles:
            - tests

    postgres:
        volumes:
            - postgres_data_test:/var/lib/postgresql/data

    elasticsearch:
        volumes:
            - es_data_test:/usr/share/elasticsearch/data

    redis:
        volumes:
            - redis_data_test:/data

volumes:
    postgres_data_test:
    es_data_test:
    redis_data_test:
