services:
    adminpanel:
        environment:
            - ENVIRONMENT=development
        volumes:
            - ./adminpanel/src:/app
        ports:
            - ${ADMINPANEL_APP_PORT}:8000
    search:
        environment:
            - ENVIRONMENT=development
        volumes:
            - ./search/src:/app
        ports:
            - ${SEARCH_APP_PORT}:8000
    postgres:
        volumes:
            - pgdata_dev:/var/lib/postgresql/data
        ports:
            - ${POSTGRES_PORT}:5432
    es:
        volumes:
            - esdata01_dev:/usr/share/elasticsearch/data
        ports:
            - ${ELASTIC_PORT}:9200
    redis:
        ports:
            - ${REDIS_PORT}:6379

volumes:
    pgdata_dev:
    esdata01_dev:
