[tool.poetry]
name = "com.docker.devenvironments.code"
version = "0.1.0"
description = "Online cinema"
authors = ["Denis <dfgaraev@yandex.ru>"]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.1"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
flake8 = "^5.0.4"
pre-commit = "^2.20.0"
isort = "^5.10.1"
pep8-naming = "^0.13.2"
flake8-broken-line = "^0.5.0"
flake8-quotes = "^3.3.1"

[tool.black]
max-line-length = 110
[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
