name: Test with Docker

on:
  push:

jobs:
  test:
    name: Run tests with docker
    runs-on: ubuntu-latest
    env:
        COMPOSE_PROJECT_NAME: movies
        ENVIRONMENT: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create env file
      run: make gha-make-env-file-prod
    - name: Build docker-compose images for tests
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
      run: make ci-tests-build
    - name: Run tests for service search
      run: make ci-run-tests s=tests_search
