name: Test with Docker

on:
  push:

jobs:
  test:
    name: Run tests with docker
    runs-on: ubuntu-latest
    env:
        COMPOSE_PROJECT_NAME: movies
        ENVIRONMENT: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Create env file
      run: @printf "${{ secrets.ENVS_PROD }}" >> .envs/production/.env
    - name: Show config
      run: make ci-tests-config
#    - name: Build docker-compose images for tests
#      run: make ci-tests-build
#    - name: Run tests for service search
#      run: make ci-run-tests s=tests_search
