name: Test with Docker workflow

on:
    pull_request:

jobs:
    test:
        name: Tests with docker
        runs-on: ubuntu-latest
        env:
            COMPOSE_PROJECT_NAME: movies
            ENVIRONMENT: production
            DOCKER_BUILDKIT: 1
        steps:
            -   name: Checkout
                uses: actions/checkout@v3
            -   name: Create env file
                run: printf "${{ secrets.ENVS_PROD }}" >> .env
            -   name: Build docker-compose images
                run: make tests-docker
