name: Test with Docker

on:
  push:

jobs:
  test:
    name: Run tests with docker
    runs-on: ubuntu-latest
    env:
        COMPOSE_PROJECT_NAME: movies
        ENVIRONMENT: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
#    - name: Create env file
#      run: make gha-make-env-file-prod
#    - name: Create env file
#      uses: "DamianReeves/write-file-action@master"
#      with:
#          path: .envs/production/.env
#          write-mode: overwrite
#          contents: |
#            ${{ secrets.ENVS_PROD }}

    - run: printf "$ENVS_PROD" >> .envs/production/.env
#    - run: printf $ENVS_PROD
    - name: Show env file
      run: make ci-show-envs-prod
    - run: cat .envs/production/.env
    - name: Show config
      run: make ci-tests-config
#    - name: Build docker-compose images for tests
#      run: make ci-tests-build
#    - name: Run tests for service search
#      run: make ci-run-tests s=tests_search
